[feat/navigation] 내비게이션 바 기능/ 해당 페이지 아이콘 활성화 기능
SOPT-WEBnB/airbnb-frontend pull request #11
Opened 2022-06-01 12:36 UTC by Brokyeom

## ✅ PR check list
- [x] PR 제목은 **[브랜치 이름] 작업 내용 한 줄 요약**으로 설정해 주세요.
- [x] develop branch로 요청했는지 확인해 주세요.
- [x] Reviewers, Assignees, Labels를 등록해 주세요.
- [ ] PR이 승인된 경우 해당 브랜치는 삭제 부탁드립니다.
 
## 📋 작업 내용
- [x] ~ NavBar 기능 구현
- [x] ~ NavBar 스타일링
- [x] ~ Home, WishList 컴포넌트 렌더시 해당 아이콘 활성화 기능 구현 

## 📌 PR Point
- 마지막까지 나를 고통스럽게 했던 NavBar 아이콘 색상 변경,, 드디어 해냈습니다.(여자친구가 큰 도움 줬습니다. 땡큐!)
- isActive props 를 각각의 컴포넌트에 넘겨줌으로써 props 값에 따라 활성화되는 아이콘이 변경되도록 코드를 작성했습니다.
- 코드를 조금 더 깔끔하게 정리할 수 있는 방법이 있다면 알려주세요!!(isActive 변수가 WishList 와 Home 에 각각 선언되어 있어서 이것을 간결하게 관리할 수 있는 방법이 있는지???)

## 📸 스크린샷 / GIF / 동영상

https://user-images.githubusercontent.com/97586683/171405114-4f7b681e-a9fd-4d12-9ab8-b0a8b0ccd187.mp4

2022-06-01 17:59 UTC, 100Gyeon requested changes

2022-06-01 17:59 UTC, 100Gyeon commented on src/components/common/NavBar.jsx
> +    font-weight: bold;
bold 대신 디자이너 분들이 피그마에 정해주신 값을 적어주시면 좋을 것 같습니다..!

2022-06-01 17:59 UTC, 100Gyeon commented on src/pages/WishList.jsx
> +  const isActive = false;
의미상으로 따지자면 wishlist 버튼은 지금 active 상태이기 때문에 false 값이 옳지 않습니다.

2022-06-01 17:59 UTC, 100Gyeon commented on src/pages/WishList.jsx
> +      <NavBar isActive={isActive} />
따라서 `<NavBar category="wishlist" />` 이런 식으로 넘겨준 뒤 NavBar 컴포넌트에서 active 여부를 판단하는 것이 좋을 것 같습니다.

2022-06-01 18:17 UTC, 100Gyeon commented
리팩터링한 부분에서 궁금한 내용 있으면 질문 남겨주세요.
컴포넌트의 props를 읽어와서 스타일링하는 방법을 조금 더 공부하면 좋을 것 같습니다.

수고하셨습니다!

2022-06-01 18:18 UTC, 100Gyeon approved these changes

2022-06-02 03:12 UTC, Brokyeom commented
> 리팩터링한 부분에서 궁금한 내용 있으면 질문 남겨주세요. 컴포넌트의 props를 읽어와서 스타일링하는 방법을 조금 더 공부하면 좋을 것 같습니다.
> 
> 수고하셨습니다!

진짜 props 넘기는 방법도 깔끔하고 많이 배운다... 감사합니다^^7

2022-06-02 14:04 UTC, merged