**Feat/home**
SOPT-WEBnB/airbnb-frontend pull request #2
Opened 2022-05-17 19:06 UTC by Brokyeom

## ✅ PR check list
- [x] PR 제목은 **[브랜치 이름] 작업 내용 한 줄 요약**으로 설정해 주세요.
- [x] develop branch로 요청했는지 확인해 주세요.
- [x] Reviewers, Assignees, Labels를 등록해 주세요.
- [] PR이 승인된 경우 해당 브랜치는 삭제 부탁드립니다.
 
## 📋 작업 내용
- [x] ~ develop branch 항목 merge 후 작업
- [x] ~ 홈 화면 기능 구현
- [x] ~ 페이지 구조화 및 스타일링
- [x] ~ 파일명 및 컴포넌트명 develop branch 의 스타일로 통일

## 📌 PR Point
1. 전체적으로 스타일링을 다시 했습니다. - 지연이 스타일링 보고 싹 뜯어 고쳤습니다. 땡큐!!!!
2. 파일명, 컴포넌트명을 develop branch 에 먼저 올라온 이름대로 통일했습니다.(ex.  파일명 HomeNavBar.jsx -> HomeFooter.jsx ,  컴포넌트명 StyledBookingBox -> StyledFirstSection) -- 확실히 모호한 단어보다 정확한 구역을 네이밍 해주는 것이 좋다는 생각이 들었습니다
3. 먼저 지연이가 머지한 develop branch 를 feat/home 에 머지하여 작업했습니다.

styled-component 로 구역을 더 깔끔하게 나눌 수 있을 것 같은데 혹시 더 좋은 구역 설정 방법 있으면 알려주세요!
다른 컴포넌트, 기능 구현 최대한 빠르게 해보겠습니다.

## 📸 스크린샷 / GIF / 동영상

https://user-images.githubusercontent.com/97586683/168890653-7e4c1bfa-cc01-41fb-bfd5-b6f92f957efa.mp4

2022-05-18 15:10 UTC, 100Gyeon requested changes
수고했어 !!! 👏

2022-05-18 15:10 UTC, 100Gyeon commented on src/assets/index.js
> +export { default as icMassage } from './icons/ic_massage.svg';
여기 오타가 있구만! 수정 부탁해 ㅎㅎ

```suggestion
export { default as icMessage } from './icons/ic_message.svg';
```

2022-05-18 15:10 UTC, 100Gyeon commented on src/components/home/HomeFooter.jsx
> +      <Link to={'./Wish'}>
```suggestion
      <Link to='/wish'>
```
이렇게 수정해 주세요!

2022-05-18 15:10 UTC, 100Gyeon commented on src/components/home/HomeFooter.jsx
> +      <Link to={'./'}>
여기도 마찬가지로 { } 필요 없고 그냥 "/"만 해주면 돼!
```suggestion
      <Link to="/">
```

2022-05-18 15:10 UTC, 100Gyeon commented on src/components/home/HomeFooter.jsx
> +        <img src={icProfile} alt="" />
```suggestion
        <img src={icProfile} />
```
여기 alt="" 빼도 좋을 것 같아!

2022-05-18 15:17 UTC, 100Gyeon commented on src/components/home/HomeInfo.jsx
> +            <span>2021년 6월 17일 - 2021년 7월 1일</span>
정말 사소한 내용이지만,, 피그마 확인해 보니까 띄어쓰기 있는 게 좋을 것 같아서 남겨!
```suggestion
            <p>Geunhwa-dong, Chuncheon</p>
            <span>2022년 1월 12일 - 2022년 1월 14일</span>
          </div>
          <div>
            <p>joyang-dong, Sokcho</p>
            <span>2021년 12월 5일 - 2021년 12월 6일</span>
          </div>
          <div>
            <p>jayang-dong, Daejeon</p>
            <span>2021년 6월 17일 - 2021년 7월 1일</span>
```

2022-05-18 15:17 UTC, 100Gyeon commented on src/components/home/HomeInfo.jsx
> +  width: 18.1rem;
![image](https://user-images.githubusercontent.com/58380158/169076940-0a45f1f5-1f5a-45ee-a676-ad4e238d4dd6.png)
지금 `width: 18.1rem;` 때문에 14일이 아니라 14(줄바꿈)일로 나오고 있네 !!
`width: 18.1rem;` 부분은 지워줘도 괜찮을 것 같습니다 👀

2022-05-18 15:22 UTC, 100Gyeon commented on src/components/home/HomeFooter.jsx
> +  border: 0.1rem solid ${(props) => props.theme.colors.airGray2};
```suggestion
  border-top: 0.1rem solid ${(props) => props.theme.colors.airGray2};
```
border-top만 해줘도 됩니다 !! ☺️

2022-05-18 15:28 UTC, 100Gyeon commented
![image](https://user-images.githubusercontent.com/58380158/169080476-60b0455c-73f7-49af-8654-23acf9da57ea.png)

혹시 이 HomeFooter.jsx를 공통(common) 컴포넌트가 아닌 home의 컴포넌트로 만든 이유가 있을까 ?!
내가 피그마 확인해 보니까 wish 페이지에서도 이 컴포넌트가 필요해서 공통 컴포넌트로 수정하는 게 좋을 것 같아 ~

![image](https://user-images.githubusercontent.com/58380158/169080931-aa063a20-5d62-4e0f-9328-26ac5a1e1d7f.png)

2022-05-18 15:44 UTC, Brokyeom commented
> ![image](https://user-images.githubusercontent.com/58380158/169080476-60b0455c-73f7-49af-8654-23acf9da57ea.png)
> 
> 혹시 이 HomeFooter.jsx를 공통(common) 컴포넌트가 아닌 home의 컴포넌트로 만든 이유가 있을까 ?! 내가 피그마 확인해 보니까 wish 페이지에서도 이 컴포넌트가 필요해서 공통 컴포넌트로 수정하는 게 좋을 것 같아 ~
> 
> ![image](https://user-images.githubusercontent.com/58380158/169080931-aa063a20-5d62-4e0f-9328-26ac5a1e1d7f.png)

아 맞네맞네 공통 컴포넌트로 수정할게!!

2022-05-19 14:52 UTC, 100Gyeon approved these changes

2022-05-19 14:55 UTC, choiyoorim approved these changes

2022-05-19 14:55 UTC, merged