[feat/wish] Wish 페이지 구현
SOPT-WEBnB/airbnb-frontend pull request #3
Opened 2022-05-18 14:49 UTC by choiyoorim

## ✅ PR check list
- [x] PR 제목은 **[브랜치 이름] 작업 내용 한 줄 요약**으로 설정해 주세요.
- [x] develop branch로 요청했는지 확인해 주세요.
- [x] Reviewers, Assignees, Labels를 등록해 주세요.
- [x] PR이 승인된 경우 해당 브랜치는 삭제 부탁드립니다.
 
## 📋 작업 내용
- [x] wish 페이지 기본 리스트 뷰 구현
- [x] 스타일 추가
- [x] json에 카테고리 내용 추가 

## 📌 PR Point
- WishListInfo 내부에 StyledCategoryInfo부분을 따로 컴포넌트로 뽑아내고 싶었는데 왜인지 잘되지가 않았습니다. 그래서 내부가 조금 가독성이 떨어지고 비효율적인 부분이 있는 것 같은데 한 번 봐주시면 좋을 것 같습니다.
- styled를 피그마 보면서 해봤는데 제 뷰가 묘하게 더 비어있는 느낌... 무언가 설정을 잘못한건지 아니면 아직 밑에 부분이 들어오지 않아서 그런건지 모르겠습니다...

## 📸 스크린샷 / GIF / 동영상
![image](https://user-images.githubusercontent.com/65010481/169070706-9f7d1ce2-24ec-49dc-9092-6bd101f174a6.png)

2022-05-18 16:20 UTC, 100Gyeon requested changes
수고했어 ✨

2022-05-18 16:20 UTC, 100Gyeon commented on src/components/common/Router.js
> +import WishList from 'pages/WishList';
```javascript
import Wish from 'pages/Wish';
```
이거는 안 쓰이고 있으니까 지워주기!

2022-05-18 16:20 UTC, 100Gyeon commented on src/components/wishlist/WishListInfo.jsx
> +        <img src={image}></img>
```suggestion
        <img src={image} />
```
그냥 바로 닫아줘도 좋을 것 같아! (self-closing)

2022-05-18 16:20 UTC, 100Gyeon commented on src/pages/WishList.jsx
> +    console.log(data);
console.log는 지워주세용 👀

2022-05-18 16:20 UTC, 100Gyeon commented on src/components/wishlist/WishListHeader.jsx
> +`;
지금 div 안에 span이 들어있는 구조인데 그냥 바로 h1 사용하는 건 어떨까?
```suggestion
function WishListHeader() {
  return <StyledWishListHeader>위시리스트</StyledWishListHeader>;
}

export default WishListHeader;

const StyledWishListHeader = styled.h1`
  padding: 4rem 2.2rem;
  font-size: 2rem;
  line-height: 2.4rem;
  font-weight: 600;
  width: 100%;
`;
```

2022-05-18 16:20 UTC, 100Gyeon commented on src/components/wishlist/WishListInfo.jsx
> +  padding: 10.4rem 2.2rem;
```suggestion
  padding: 0 2.2rem;
```
위에 Header 수정하면 이렇게 바꿔주셔도 됩니당!

2022-05-18 16:20 UTC, 100Gyeon commented on src/components/wishlist/WishListInfo.jsx
> +  border-style: dashed;
피그마 보면 dashed가 필요없는 것 같은데 어떤 이유로 넣게 되었는지 궁금해!

2022-05-18 16:27 UTC, 100Gyeon commented on src/components/wishlist/WishListHeader.jsx
> +`;
담부터는 px 말고 rem 썼는지 한 번 더 확인해 주세용 ☺️

2022-05-18 16:36 UTC, Brokyeom approved these changes

2022-05-18 16:36 UTC, Brokyeom commented on src/pages/WishList.jsx
> +      <WishListInfo list={categoryList}></WishListInfo>
```suggestion
      <WishListHeader />
      <WishListInfo list={categoryList} />
```

여기도 self-closing 하면 될듯해!!

2022-05-18 17:11 UTC, 100Gyeon reviewed
>WishListInfo 내부에 StyledCategoryInfo부분을 따로 컴포넌트로 뽑아내고 싶었는데 왜인지 잘되지가 않았습니다. 그래서 내부가 조금 가독성이 떨어지고 비효율적인 부분이 있는 것 같은데 한 번 봐주시면 좋을 것 같습니다.

이 부분은 아래 코드 참고해줘 😉

2022-05-18 17:11 UTC, 100Gyeon commented on src/components/wishlist/WishListInfo.jsx
> +}
```suggestion
function WishListInfo({ list }) {
  return (
    <StyledWishListInfo>
      <StyledCategoryInfo>
        {list.map(({ id, image, title }) => (
          <li key={id}>
            <img src={image} />
            <span>{title}</span>
          </li>
        ))}
      </StyledCategoryInfo>
    </StyledWishListInfo>
  );
}
```

2022-05-18 17:14 UTC, 100Gyeon commented on src/components/wishlist/WishListInfo.jsx
> +  }
여기에 `object-fit: cover;`도 추가해줘! 🙆‍♀️

2022-05-18 17:15 UTC, 100Gyeon commented on src/components/wishlist/WishListInfo.jsx
> +  }
border-radius도 rem 단위 맞춰서 0.8rem으로 수정하자!

2022-05-19 14:46 UTC, 100Gyeon approved these changes

2022-05-19 14:49 UTC, merged