[feat/booking]예약 기능 구현
SOPT-WEBnB/airbnb-frontend pull request #4
Opened 2022-05-19 18:12 UTC by Brokyeom

## ✅ PR check list
- [x] PR 제목은 **[브랜치 이름] 작업 내용 한 줄 요약**으로 설정해 주세요.
- [x] develop branch로 요청했는지 확인해 주세요.
- [x] Reviewers, Assignees, Labels를 등록해 주세요.
- [x] PR이 승인된 경우 해당 브랜치는 삭제 부탁드립니다.
 
## 📋 작업 내용
- [x] ~ 예약 기능 구현
- [x] ~ 페이지 구조화 및 스타일링 

## 📌 PR Point
- Room 컴포넌트에서 가져온 props 들을 이용해서 예약하기 버튼을 눌렀을때 라우팅, useLocation Hook을 통해 Home/FirstSection 컴포넌트에 Room 의 title, host props 가 전달되며 Home 화면에서 해당하는 방의 정보를 렌더합니다.
- develop branch 의 코드를 머지하여 합친 코드입니다.
- 이제 문제는 예약하기 버튼을 눌렀을 때, 로딩화면이 떴다가 Home 으로 가야하는데, 이 중간에 로딩화면을 어떻게 넣어야 할지 고민...
- title, host props가 여기저기 좀 많이 이동하는 느낌,, ( Room -> RoomFooter -> Home -> HomeInfo -> FirstSection ) 과정을 간소화 할 방법이 어떤것들이 있을까?

## 📸 스크린샷 / GIF / 동영상

https://user-images.githubusercontent.com/97586683/169370133-639dae74-0e04-41e5-bfd5-422a9d699389.mp4

2022-05-19 18:21 UTC, Brokyeom commented on src/components/room/RoomFooter.jsx
> +      <Link to={'/'} state={{ title: { title }, host: { host } }}>
```suggestion
      <Link to="/" state={{ title: { title }, host: { host } }}>
```
이거이거 또 이렇게 돼있었네

2022-05-19 18:22 UTC, 100Gyeon commented on src/components/room/RoomFooter.jsx
> +      <Link to={'/'} state={{ title: { title }, host: { host } }}>
ㅋㅋㅋㅋㅋ 셀프 리뷰 좋아요 ^^ 수정해서 다시 푸시하면 돼!

2022-05-19 21:57 UTC, 100Gyeon requested changes
수고했어 !!👍
지금 conflict 있다고 하니까 develop 브랜치에서 pull 받아서 확인해줘~
![image](https://user-images.githubusercontent.com/58380158/169411238-2f5dae22-ff74-4086-a1a5-725da8dac515.png)

2022-05-19 21:57 UTC, 100Gyeon commented on src/components/home/FirstSection.jsx
> +}
이런 경우에는 삼항 연산자 활용해서 아래처럼 쓰는 게 더 좋습니다!

```suggestion
function FirstSection({ title, host }) {
  return (
    <>
      {title === 'unBooked' ? (
        <StyledFirstSection>
          <StyledIcHand src={icHand} />
          <span>아직 예약된 여행이 없습니다!</span>
          <StyledSearchButton>숙소 검색하기</StyledSearchButton>
        </StyledFirstSection>
      ) : (
        <StyledIsBooked>
          <img src={imgRoom} />
          <p>{title}</p>
          <span>{host} 님이 호스팅 하는 집 전체</span>
        </StyledIsBooked>
      )}
    </>
  );
}
```

2022-05-19 21:57 UTC, 100Gyeon commented on src/components/home/FirstSection.jsx
> +  filter: drop-shadow(4px 4px 20px rgba(0, 0, 0, 0.15));
px -> rem 바꿔주세요~!

2022-05-19 21:57 UTC, 100Gyeon commented on src/components/home/FirstSection.jsx
> +  border-radius: 6px;
px -> rem 바꿔주세요~!

2022-05-19 22:12 UTC, 100Gyeon requested changes

2022-05-19 22:12 UTC, 100Gyeon commented on src/components/room/RoomFooter.jsx
> +      </Link>
title, host 따로 전달하지 않고 roomInfo로 전달해도 좋을 것 같습니다
```suggestion
      <Link to="/" state={{ roomInfo: { title, host } }}>
        <button>예약하기</button>
      </Link>
```

2022-05-19 22:12 UTC, 100Gyeon commented on src/pages/Home.jsx
>    );
이 부분은 아래처럼 간결하게 수정할 수 있습니다
```javascript
const location = useLocation();
const { roomInfo } = location.state;

return (
  <StyledHome>
    <HomeInfo title={roomInfo?.title ?? 'unBooked'} host={roomInfo?.host ?? 'unBooked'} />
    <NavBar />
  </StyledHome>
);
```

2022-05-19 22:31 UTC, 100Gyeon reviewed
>이제 문제는 예약하기 버튼을 눌렀을 때, 로딩화면이 떴다가 Home 으로 가야하는데, 이 중간에 로딩화면을 어떻게 넣어야 할지 고민...

지금 구현한 방식 보니까 mock-api.json 사용해서 post 한 게 아니고, Link 통해서 넘겨주는 방식이던데 이렇게 하면 서버랑 통신 자체가 없어서 로딩 화면이 필요 없긴 해.. 일단 이 부분은 이번 주 합동 세미나 이후에 고민해 보자!

2022-05-20 00:13 UTC, choiyoorim approved these changes

2022-05-20 00:13 UTC, choiyoorim commented on src/pages/Home.jsx
>    );
근데 ?는 어떤 연산자인가요?? 이건 제 궁금증...............

2022-05-20 04:36 UTC, Brokyeom commented on src/components/room/RoomFooter.jsx
> +      </Link>
roomInfo 로 전달하게 되면 Room 컴포넌트 에서도 roomInfo 로 넘겨줘야 할까??? 이대로만 수정하니 정보가 안넘어오네
일단 좀더 고민해볼게!!

2022-05-20 05:28 UTC, 100Gyeon commented on src/components/common/NavBar.jsx
> +      <Link to="/Wishlist">
이거 `/wishlist`가 맞아! 대문자에서 소문자로 바꿔줘야 해 😹

2022-05-20 05:32 UTC, 100Gyeon commented on src/components/room/RoomFooter.jsx
> +      </Link>
`Uncaught TypeError: Cannot destructure property 'roomInfo' of 'state' as it is null.` 이게 뜨고 있었네 😂
state가 null일 수도 있는데 구조 분해 할당하려고 하니까 뜨는 타입 에러여서 아래처럼 수정하면 돼!

```javascript
function Home() {
  const location = useLocation();
  const state = location.state;

  return (
    <StyledHome>
      <HomeInfo title={state?.roomInfo.title ?? 'unBooked'} host={state?.roomInfo.host ?? 'unBooked'} />
      <NavBar />
    </StyledHome>
  );
}
```

2022-05-20 05:37 UTC, 100Gyeon commented on src/pages/Home.jsx
>    );
optional chaining이라고 해!
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/Optional_chaining
이 링크에 설명 잘 되어 있으니까 참고하면 좋을 듯 😉

2022-05-20 10:18 UTC, 100Gyeon commented on src/components/home/FirstSection.jsx
> +  border: 1px solid ${(props) => props.theme.colors.airGray2};
여기 아직 수정 안 된 것 같아!

2022-05-20 15:22 UTC, 100Gyeon approved these changes

2022-05-20 15:26 UTC, merged